name: Dotnet Stryker

on:
  push:
  pull_request:

jobs:
  stryker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dotnet tools
        run: dotnet tool restore

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Run Stryker
        run: dotnet stryker

      - name: Run stryker with specific xunit version
        run: XUNIT_PACKAGE_ID=xunit XUNIT_PACKAGE_VERSION=2.9.3 XUNIT_IS_TESTING_PLATFORM=false dotnet stryker

      - name: Run stryker with specific config file
        run: dotnet stryker -f stryker-config-slnx.json
        continue-on-error: true


